# Reconhecimento dos arquivos

In [18]:
from logistics_ops.notebooks import build_notebook_session

nb = build_notebook_session()

dataset_objects = nb.list_dataset_objects()
csv_file_names = nb.csv_file_names()
summary = nb.summarize_csvs()
summary.head()

dataframes = nb.load_csvs(["drivers.csv", "trips.csv", "loads.csv"])

for file_name, dataframe in dataframes.items():
    print(f"{file_name} | shape={dataframe.shape}")
    display(dataframe.head())

drivers.csv | shape=(150, 12)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

trips.csv | shape=(85410, 12)

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed

loads.csv | shape=(85410, 12)

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot

In [8]:
from pathlib import Path
import sys

project_root = Path.cwd()
if not (project_root / "src").exists():
    for parent in [project_root, *project_root.parents]:
        if (parent / "src").exists():
            project_root = parent
            break

src_dir = project_root / "src"
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

print(f"Project root: {project_root}")

Project root: D:\developer\workspace_python\logistics-operations

In [9]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from logistics_ops.bootstrap import build_tabular_reader

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

reader = build_tabular_reader()

In [10]:
dataset_objects = reader.list_dataset_objects()
print(f"Total de objetos encontrados: {len(dataset_objects)}")
dataset_objects[:10]

Total de objetos encontrados: 16

['raw/kaggle/yogape/logistics-operations-database/.complete/datasets/yogape/logistics-operations-database/1/bundle.complete',
 'raw/kaggle/yogape/logistics-operations-database/DATABASE_SCHEMA.txt',
 'raw/kaggle/yogape/logistics-operations-database/customers.csv',
 'raw/kaggle/yogape/logistics-operations-database/delivery_events.csv',
 'raw/kaggle/yogape/logistics-operations-database/driver_monthly_metrics.csv',
 'raw/kaggle/yogape/logistics-operations-database/drivers.csv',
 'raw/kaggle/yogape/logistics-operations-database/facilities.csv',
 'raw/kaggle/yogape/logistics-operations-database/fuel_purchases.csv',
 'raw/kaggle/yogape/logistics-operations-database/loads.csv',
 'raw/kaggle/yogape/logistics-operations-database/maintenance_records.csv']

In [11]:
csv_object_names = [object_name for object_name in dataset_objects if object_name.endswith(".csv")]
csv_file_names = [Path(object_name).name for object_name in csv_object_names]
csv_file_names

['customers.csv',
 'delivery_events.csv',
 'driver_monthly_metrics.csv',
 'drivers.csv',
 'facilities.csv',
 'fuel_purchases.csv',
 'loads.csv',
 'maintenance_records.csv',
 'routes.csv',
 'safety_incidents.csv',
 'trailers.csv',
 'trips.csv',
 'truck_utilization_metrics.csv',
 'trucks.csv']

In [14]:
dataframes = {}
for file_name in csv_file_names:
    dataframe = reader.read_csv_from_dataset(file_name)
    dataframes[file_name] = dataframe
    print(f"Arquivo: {file_name} | shape={dataframe.shape}")
    display(dataframe.head())

Arquivo: customers.csv | shape=(200, 8)

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

Arquivo: delivery_events.csv | shape=(170820, 11)

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

Arquivo: driver_monthly_metrics.csv | shape=(4464, 9)

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8

Arquivo: drivers.csv | shape=(150, 12)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

Arquivo: facilities.csv | shape=(50, 9)

,facility_id,facility_name,facility_type,city,state,latitude,longitude,dock_doors,operating_hours
0,FAC00001,Houston Distribution Center,Cross-Dock,Houston,TX,29.7604,-95.3698,125,24/7
1,FAC00002,Kansas City Hub,Cross-Dock,Kansas City,MO,39.0997,-94.5786,33,7AM-7PM
2,FAC00003,Charlotte Distribution Center,Distribution Center,Charlotte,NC,35.2271,-80.8431,138,24/7
3,FAC00004,Chicago Distribution Center,Distribution Center,Chicago,IL,41.8781,-87.6298,38,8AM-5PM
4,FAC00005,Indianapolis Hub,Distribution Center,Indianapolis,IN,39.7684,-86.1581,56,8AM-5PM

Arquivo: fuel_purchases.csv | shape=(196442, 11)

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816
3,FUEL00000004,TRIP00008465,TRK00018,DRV00047,2022-04-20 00:00:00,Memphis,NY,130.7,3.579,467.78,FC776357
4,FUEL00000005,TRIP00069700,TRK00054,NaN,2024-06-13 09:00:00,Columbus,AZ,185.3,3.422,634.10,FC391024

Arquivo: loads.csv | shape=(85410, 12)

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot

Arquivo: maintenance_records.csv | shape=(2920, 12)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive
3,MAINT00000004,TRK00056,2022-01-02,Inspection,416522,2.8,298.80,67.48,366.28,Kansas City,34.6,Emergency Inspection
4,MAINT00000005,TRK00029,2022-01-02,Repair,179968,4.6,409.08,982.59,1391.67,Omaha,4.4,Emergency Repair

Arquivo: routes.csv | shape=(58, 9)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3

Arquivo: safety_incidents.csv | shape=(170, 15)

,incident_id,trip_id,truck_id,driver_id,incident_date,incident_type,location_city,location_state,at_fault_flag,injury_flag,vehicle_damage_cost,cargo_damage_cost,claim_amount,preventable_flag,description
0,INC00000001,TRIP00036079,TRK00006,DRV00006,2023-04-09 14:00:00,Moving Violation,Columbus,PA,True,False,12629.26,0.00,12629.26,True,Severe incident involving equipment
1,INC00000002,TRIP00032462,TRK00084,DRV00006,2023-02-19 11:00:00,Moving Violation,Columbus,NC,False,False,2700.70,14284.24,16984.94,False,Severe incident involving weather
2,INC00000003,TRIP00067583,TRK00106,DRV00119,2024-05-20 01:00:00,Customer Complaint,Seattle,OK,True,False,24302.32,0.00,24302.32,True,Minor incident involving traffic
3,INC00000004,TRIP00049128,TRK00085,DRV00134,2023-09-26 03:00:00,Equipment Damage,Kansas City,TN,True,False,4879.13,0.00,4879.13,True,Moderate incident involving equipment
4,INC00000005,TRIP00062884,TRK00014,DRV00133,2024-03-20 14:00:00,DOT Violation,Las Vegas,IN,False,False,14951.40,0.00,14951.40,False,Minor incident involving other driver

Arquivo: trailers.csv | shape=(180, 9)

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas

Arquivo: trips.csv | shape=(85410, 12)

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed

Arquivo: truck_utilization_metrics.csv | shape=(3312, 10)

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422,120453.71,6.49,0,0.00,0.0,1.097
3,TRK00001,2022-04-01,20,34428,73531.28,6.50,2,3548.15,71.8,0.667
4,TRK00001,2022-05-01,16,20851,40791.53,6.38,1,1969.42,43.9,0.516

Arquivo: trucks.csv | shape=(120, 11)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta
3,TRK00004,3317,Freightliner,2015,1VV131945381692351,2017-06-17,8875,Diesel,200,Active,Salt Lake City
4,TRK00005,6731,Freightliner,2016,1FT822215709701985,2021-10-08,42042,Diesel,250,Maintenance,Miami

In [16]:
for file_name in csv_file_names:
    dataframe = dataframes[file_name]
    print(f"Arquivo: {file_name} | shape={dataframe.shape}")
    display(dataframe.info())
    print('------------------------------------------------------')

Arquivo: customers.csv | shape=(200, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    object
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), object(6)
memory usage: 12.6+ KB

None

------------------------------------------------------
Arquivo: delivery_events.csv | shape=(170820, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  object
 1   load_id             170820 non-null  object
 2   trip_id             170820 non-null  object
 3   event_type          170820 non-null  object
 4   facility_id         170820 non-null  object
 5   scheduled_datetime  170820 non-null  object
 6   actual_datetime     170820 non-null  object
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  object
 10  location_state      170820 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 13.2+ MB

None

------------------------------------------------------
Arquivo: driver_monthly_metrics.csv | shape=(4464, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   object
 1   month                  4464 non-null   object
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: float64(5), int64(2), object(2)
memory usage: 314.0+ KB

None

------------------------------------------------------
Arquivo: drivers.csv | shape=(150, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    object
 1   first_name         150 non-null    object
 2   last_name          150 non-null    object
 3   hire_date          150 non-null    object
 4   termination_date   26 non-null     object
 5   license_number     150 non-null    object
 6   license_state      150 non-null    object
 7   date_of_birth      150 non-null    object
 8   home_terminal      150 non-null    object
 9   employment_status  150 non-null    object
 10  cdl_class          150 non-null    object
 11  years_experience   150 non-null    int64
dtypes: int64(1), object(11)
memory usage: 14.2+ KB

None

------------------------------------------------------
Arquivo: facilities.csv | shape=(50, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   facility_id      50 non-null     object
 1   facility_name    50 non-null     object
 2   facility_type    50 non-null     object
 3   city             50 non-null     object
 4   state            50 non-null     object
 5   latitude         50 non-null     float64
 6   longitude        50 non-null     float64
 7   dock_doors       50 non-null     int64
 8   operating_hours  50 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 3.6+ KB

None

------------------------------------------------------
Arquivo: fuel_purchases.csv | shape=(196442, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196442 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  196442 non-null  object
 1   trip_id           196442 non-null  object
 2   truck_id          192562 non-null  object
 3   driver_id         192454 non-null  object
 4   purchase_date     196442 non-null  object
 5   location_city     196442 non-null  object
 6   location_state    196442 non-null  object
 7   gallons           196442 non-null  float64
 8   price_per_gallon  196442 non-null  float64
 9   total_cost        196442 non-null  float64
 10  fuel_card_number  196442 non-null  object
dtypes: float64(3), object(8)
memory usage: 16.5+ MB

None

------------------------------------------------------
Arquivo: loads.csv | shape=(85410, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  object
 1   customer_id          85410 non-null  object
 2   route_id             85410 non-null  object
 3   load_date            85410 non-null  object
 4   load_type            85410 non-null  object
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  object
 11  booking_type         85410 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 7.8+ MB

None

------------------------------------------------------
Arquivo: maintenance_records.csv | shape=(2920, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   object
 1   truck_id             2920 non-null   object
 2   maintenance_date     2920 non-null   object
 3   maintenance_type     2920 non-null   object
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   object
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 273.9+ KB

None

------------------------------------------------------
Arquivo: routes.csv | shape=(58, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     object
 1   origin_city             58 non-null     object
 2   origin_state            58 non-null     object
 3   destination_city        58 non-null     object
 4   destination_state       58 non-null     object
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB

None

------------------------------------------------------
Arquivo: safety_incidents.csv | shape=(170, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   incident_id          170 non-null    object
 1   trip_id              170 non-null    object
 2   truck_id             169 non-null    object
 3   driver_id            169 non-null    object
 4   incident_date        170 non-null    object
 5   incident_type        170 non-null    object
 6   location_city        170 non-null    object
 7   location_state       170 non-null    object
 8   at_fault_flag        170 non-null    bool
 9   injury_flag          170 non-null    bool
 10  vehicle_damage_cost  170 non-null    float64
 11  cargo_damage_cost    170 non-null    float64
 12  claim_amount         170 non-null    float64
 13  preventable_flag     170 non-null    bool
 14  description          170 non-null    object
dtypes: bool(3), float64(3), object(9)
memory usage: 16.6+ KB

None

------------------------------------------------------
Arquivo: trailers.csv | shape=(180, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    object
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    object
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    object
 6   acquisition_date  180 non-null    object
 7   status            180 non-null    object
 8   current_location  180 non-null    object
dtypes: int64(3), object(6)
memory usage: 12.8+ KB

None

------------------------------------------------------
Arquivo: trips.csv | shape=(85410, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  object
 1   load_id                85410 non-null  object
 2   driver_id              83696 non-null  object
 3   truck_id               83738 non-null  object
 4   trailer_id             83730 non-null  object
 5   dispatch_date          85410 non-null  object
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 7.8+ MB

None

------------------------------------------------------
Arquivo: truck_utilization_metrics.csv | shape=(3312, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   object
 1   month               3312 non-null   object
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: float64(5), int64(3), object(2)
memory usage: 258.9+ KB

None

------------------------------------------------------
Arquivo: trucks.csv | shape=(120, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    object
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    object
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    object
 5   acquisition_date       120 non-null    object
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    object
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    object
 10  home_terminal          120 non-null    object
dtypes: int64(4), object(7)
memory usage: 10.4+ KB

None

------------------------------------------------------

In [17]:
schema_file_name = "DATABASE_SCHEMA.txt"
if schema_file_name in [Path(object_name).name for object_name in dataset_objects]:
    schema_text = reader.read_text_from_dataset(schema_file_name)
    print(schema_text)
else:
    print("DATABASE_SCHEMA.txt não encontrado no dataset.")

LOGISTICS DATABASE SCHEMA
=========================

1. DRIVERS
   - Primary Key: driver_id
   - Contains: Driver demographics, employment history, license info

2. TRUCKS
   - Primary Key: truck_id
   - Contains: Fleet equipment details, acquisition info, status

3. TRAILERS
   - Primary Key: trailer_id
   - Contains: Trailer inventory, types, status

4. CUSTOMERS
   - Primary Key: customer_id
   - Contains: Customer accounts, contract types, revenue potential

5. FACILITIES
   - Primary Key: facility_id
   - Contains: Terminal and warehouse locations, capacity

6. ROUTES
   - Primary Key: route_id
   - Contains: Origin-destination pairs, distances, rate structures

7. LOADS
   - Primary Key: load_id
   - Foreign Keys: customer_id, route_id
   - Contains: Shipment details, revenue, booking type

8. TRIPS
   - Primary Key: trip_id
   - Foreign Keys: load_id, driver_id, truck_id, trailer_id
   - Contains: Actual trip performance, fuel consumption, duration

9. FUEL_PURCHASES
   - Primary Key: fuel_purchase_id
   - Foreign Keys: trip_id, truck_id, driver_id
   - Contains: Fuel transactions, prices, locations

10. MAINTENANCE_RECORDS
    - Primary Key: maintenance_id
    - Foreign Keys: truck_id
    - Contains: Service history, costs, downtime

11. DELIVERY_EVENTS
    - Primary Key: event_id
    - Foreign Keys: load_id, trip_id, facility_id
    - Contains: Pickup/delivery timestamps, detention, on-time status

12. SAFETY_INCIDENTS
    - Primary Key: incident_id
    - Foreign Keys: trip_id, truck_id, driver_id
    - Contains: Accidents, violations, damage costs

13. DRIVER_MONTHLY_METRICS (Aggregated)
    - Composite Key: driver_id, month
    - Contains: Monthly performance summaries per driver

14. TRUCK_UTILIZATION_METRICS (Aggregated)
    - Composite Key: truck_id, month
    - Contains: Monthly equipment utilization summaries

KEY RELATIONSHIPS:
- loads -> customers (many-to-one)
- loads -> routes (many-to-one)
- trips -> loads (one-to-one)
- trips -> drivers (many-to-one)
- trips -> trucks (many-to-one)
- trips -> trailers (many-to-one)
- fuel_purchases -> trips (many-to-one)
- maintenance_records -> trucks (many-to-one)
- delivery_events -> trips (many-to-one)
- safety_incidents -> trips (many-to-one)

ANALYTICAL USE CASES:
1. Driver performance: On-time rates, MPG, revenue per mile
2. Route profitability: Revenue vs costs by lane
3. Fleet utilization: Miles per truck, revenue per asset
4. Maintenance analysis: Cost per mile, downtime impact
5. Fuel efficiency: MPG trends, fuel cost by route
6. Customer analysis: Revenue by customer, service levels
7. Safety metrics: Incident rates, preventable accidents
8. Seasonal patterns: Load volume, rate fluctuations